language: python

python:
  - 2.7

env:
  - DJANGO=1.8.7

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  coverage run --source=alapage setup.py test

after_success:
  coveralls
