language: python

python:
  - 2.7

env:
  global:
    - DJANGO_SETTINGS_MODULE="django-alapage.travis_settings"
    - PYTHONPATH="/home/travis/build/synw/django-alapage"
  matrix:
    - DJANGO=1.11.8

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  coverage run --source=alapage setup.py test

after_success:
  coveralls
