language: python

python:
  - 2.7

env:
  - DJANGO=1.8.6

install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=alapage manage.py test
after_success:
  coveralls
#script: 
#  - python setup.py test
