# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jssor', '0001_initial'),
        ('alapage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slideshow_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jssor.ResponsiveGroup', verbose_name='Slideshow'),
        ),
    ]
